name: News Push Bot

on:
  schedule:
    # 每天北京时间早上 8:00 运行 (由于服务器在国外，这里填的是 UTC 时间 0:00)
    - cron: '0 0 * * *' 
  workflow_dispatch: # 加上这行，你的 GitHub 页面就会多出一个手动运行的按钮

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          DINGTALK_WEBHOOK: ${{ secrets.DINGTALK_WEBHOOK }}
        run: python main.py
